### PR TITLE
Use uintptr instead of uint64 to support 32 bit systems with same cod…

### PR DESCRIPTION
**Pull request by cornelk**
This should allow to use the hashmap on 32 bit systems without need of copying the codebase to files that use 32 bit instead of 64 bit variables.

@edhemphill  please test and review

### CODE REVIEW

**Comment by edhemphill** [comment]
OK - will do. Give me about 24 hrs

**Comment by edhemphill** [comment]
Looks like we have an issue. I'll dig into it.

32-bit armel hardware:

```root@wigwagrelay:~/go-workspace/src/github.com/cornelk/hashmap# go test
# github.com/cornelk/hashmap
./hashmap_test.go:246: constant 4611686018427387904 overflows uintptr
./hashmap_test.go:250: constant 4611686018427387904 overflows uintptr
./hashmap_test.go:253: constant 4611686018427387904 overflows uintptr
./hashmap_test.go:256: constant 4611686018427387904 overflows uintptr
FAIL	github.com/cornelk/hashmap [build failed]
```

**Comment by edhemphill** [comment]
probably can fix this by just pulling your constants out to an arch dependent file.

**Comment by cornelk** [comment]
I pushed a fix

**Comment by edhemphill** [comment]
```
root@wigwagrelay:~/go-workspace/src/github.com/cornelk/hashmap# go test

--- FAIL: TestInsert (0.00s)
	hashmap_test.go:59: ok should be true for item stored within the map.
--- FAIL: TestStringer (0.00s)
	hashmap_test.go:148: 1 item map as string does not match: [1603798735]
	hashmap_test.go:154: 2 item map as string does not match: [1603798735,2347111925]
FAIL
exit status 1
FAIL	github.com/cornelk/hashmap	0.025s
```

**Comment by edhemphill** [comment]
clever fix on the constants. You might want to verify the language spec to make sure `IntSize` is always the same as `uintptr` - another way I supposed would be to use `unsafe.SizeOf()`

**Comment by cornelk** [comment]
I will investigate the problems with a 32 bit version of Go and come back to you later.

**Comment by cornelk** [comment]
Should be fixed, 32 bit Windows version of Go passes the test

**Comment by cornelk** [comment]
@edhemphill please try again.

**Comment by edhemphill** [comment]
Will do @cornelk  - sorry for delay. Just FYI - the benchmarks don't run on my 32-bit ARM platform b/c it only has 512mb of RAM. I need to modify that to fit the memory.

**Comment by cornelk** [comment]
Sure. This pull request is about testing the 32 bit compatibility, if it works I will merge it. The hashing benchmarks are only relevant in case that we will change the hashing.

**Comment by cornelk** [comment]
The code works, so I will merge it. When you can figure details about the segmentation fault you can create a new ticket with more information about it.

**Comment by edhemphill** [comment]
Right on

**Pull request merged**
